name = "roll-doradobonus-casino"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=roll-doradobonus.casino"
HMAC_KEY = "820169345f5c07f12aeb1fff5112bbcfd1a91377ae81132c4795176be363a95d"
COOKIE_NAME = "6cr"
PLAY_PATH = "launch"
BUTTON_ID = "p252de41408f0f9555e007a12f6588120"
GATE_SALT = "a74fd6cc92cd0922"
